version: '3.8'

services:
    wevensio:
        build: 
            context: .
            args: 
                - NODE_ENV=development

        ports:
            - 5001:5001

        entrypoint: [ "npm", "run", "dev" ]

        environment:
            - NODE_ENV=development
            - PORT=5001
            - SUBSCRIBE=subscribe.default
            - CHANNELS=on_add_user
            - SOCKET_IO_CORS_ORIGIN=*
            - REDIS_URL=redis://cache:6379

        volumes:
            - ./src:/service/src

        networks:
            - wevensio

        # env_file:
        #     - path: ./.env
        #       required: true # default

    cache:
        image: redis/redis-stack:latest
        restart: always
        ports:
            - '6379:6379'
            - '8001:8001'
        volumes:
            - cache:/data

        networks:
            - wevensio

volumes:
  cache:
    driver: local

networks:
    wevensio:
        driver: bridge
